services:
  seclens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seclens_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://seclens:seclenspass@postgres:5432/seclens_db?schema=public
      - NEXTAUTH_SECRET=seclens_docker_jwt_supersecret_key_2026
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: seclens_postgres
    environment:
      POSTGRES_USER: seclens
      POSTGRES_PASSWORD: seclenspass
      POSTGRES_DB: seclens_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seclens -d seclens_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
